进入以太坊章节第一部分内容审稿
mochain/ethereumhelp pull request #2
Opened 2019-01-13 15:55 UTC by ysqi

完成内容：进去以太坊世界
- [x] 什么是以太坊
- [x] 以太坊愿景
- [x] 以太坊发展历史
- [ ] 以太坊创始人介绍

2019-01-14 01:18 UTC, gitferry requested changes

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +以太坊是全新的、开源的、具有智能合约功能的区块链技术系统（如比特币），尝试构建基于交易的状态机。同时，以太坊致力于为开发者提供一个紧密整合的的端到端系统，这个系统提供一个可信对象消息传递技术框架，使开发者可以用一种前所未有的计算范式来构建应用。其最重要目标是促进那些原本无法信任对方的个体之间的交易。以太坊的在数字货币领域的创新，标致着区块链2.0的到来。
感觉第一句话有点别扭，我觉得这种通俗科普文不太适合引入像“状态机”、“端到端系统”、“计算范式”这样专业的词汇。我觉得第一段只要介绍以太坊是在比特币基础上发展的，一种智能合约平台就可以。

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
>  ![以太坊](/images/content/ethereum-home.png)
图片链接是不是有问题？是不是需要加上"."变成"./images/xxxxx"

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +然后，在2014年通过网上公开募资得到开发资金，投资人用比特币向基金会购买以太币。最初以太坊程序是由一间位在瑞士的公司 Ethereum Switzerland GmbH 开发[^2]，之后转移至一个非营利机构“以太坊基金会”（Ethereum Foundation）。
第一句话缺少主语，“在2014年，以太坊团队为了获取开发资金，通过由比特币换取以太币的方式公开募资，也就是后来风行一时的ICO（Initial Coin Offering）。”

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
>  ---
有一个建议是，在写作的时候一句话占一行，方便写review意见。

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +1. 以太坊公链在2015年7月30日启动。最初的以太坊版本称为边境（Frontier，也有“前锋”的意思），用的是工作量证明（proof-of-work）算法，但未来预期会转换成权益证明（proof-of-stake）。此时的以太坊还不太成熟，但是可以进行基本的挖矿，学习和试验。系统运行之后，吸引了更多的人关注并参与到开发中来，以太坊作为一个应用平台，需要更多的人去开发自己的去中心化应用来实现
倒数第二句，“参与到开发中来”后面应该用句号

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +因此，区块链作为分布式数据库就能在整个网络中维持一致。所有交易活动受到密码保护，利用程序化的经济激励来刺激更多的人来维护和验证网络，保障区块链的安全与去中心化。
“所有交易活动受到密码保护”很容易让人以为所有交易是加密的，应该说“所有交易都会被签名以保证不可抵赖性”

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +比特币系统视为一个分布式账本，账本中记录着每个账户的资金流水，可实时统计账户余额并通过交易将比特币进行转移，实现个体间无需信任基础和第三方中介的金融活动。比特币简单有效的解决了分布式网络的共识问题，随着更多开发者关注，极客们希望将比特币系统用于数字货币转移之外的其他经济活动。
第一句话有些问题，首先比特币中是没有账户的概念的，可以说“账本中记录着每笔交易的动态”，另外也不是“实时统计”的，这些容易误导读者。

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +2014年， Vitalik Buterin 和 Gavin Wood、Jeffrey Wilcke 完成新平台的架构设计与运行规则，通过实施图灵完备的语言实现一个区块链架构的可编程的智能合约平台，该平台即为当前高热度的以太坊。
“通过实施图灵完备的语言实现一个区块链架构的可编程的智能合约平台”不通顺，
建议改成“构建了一个支持图灵完备语言的智能合约平台”

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +超前的概念，在当时未能有系统能实现，区块链技术确让大家看到了希望，以太坊引入智能合约，实现经济活动的可编程性和抹除金融中介。
“确”=>“却”

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +以太坊衍生了**Token 经济**，是区块链技术从只能进行数字货币的转移时代迈入了智能合约时代。
“是”=>“使”

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +**以太坊是可编程的区块链**，不同于比特币中预设的货币转移操作。在以太坊中用户可自定义一份操作，以满足自身业务需求。从而可以在以太坊网络中部署运行风格各异的应用程序，此时以太坊便是一个应用平台，是分散的、去中心化的。
个人认为这段话不太严谨，首先“目前区块链是不可编程的”，这里区块链是否可编程一般指的是你是否可以自定义区块链的设置，例如出块时间等。而我们说的可编程是说以太坊EVM可以支持图灵完备的编程语言Solidity，而且这里提到图灵完备的话要解释什么是图灵完备。

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +一份自定义操作如何得以运行，依赖的是以太坊内置的可编程性。以太坊中定义并实现一套这些操作指令行为协议，协议内嵌在以太坊程序中，当交易需要打包到区块中时，以太坊将启动一个包含协议的子系统，将按照交易信息让子系统执行智能合约中的操作指令。这个子系统名为“EVM”，在计算机技术上称之为“虚拟机”，在沙盒环境中正确执行操作指令，是“图灵完备的”。
建议加上EVM的完整单词，Ethereum Virtual Machine。

2019-01-14 01:18 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +这样，开发者便可以利用熟悉的编程语言编写可以运行在以太坊虚拟机上的应用。以太坊作为分布式的区块链网络，所有交易均在所有节点中由虚拟机以相同的指令执行。
我熟悉C++并不能在以太坊虚拟机上运行啊

2019-01-14 15:19 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
>  ![以太坊](/images/content/ethereum-home.png)
图片连接无问题，是hugo下的写法
```suggestion
![以太坊](/images/content/ethereum-home.png)
```

2019-01-14 15:25 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +然后，在2014年通过网上公开募资得到开发资金，投资人用比特币向基金会购买以太币。最初以太坊程序是由一间位在瑞士的公司 Ethereum Switzerland GmbH 开发[^2]，之后转移至一个非营利机构“以太坊基金会”（Ethereum Foundation）。
```suggestion
然后，在2014年，以太坊团队为了获取开发资金，通过由比特币换取以太币的方式公开募资，也就是后来风行一时风的ICO（Initial Coin Offering）。
最初以太坊程序是由一间位在瑞士的公司 Ethereum Switzerland GmbH 开发[^2]，之后转移至一个非营利机构“以太坊基金会”（Ethereum Foundation）。
```

2019-01-14 15:29 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
>  ---
好主意，👍

2019-01-14 15:30 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +超前的概念，在当时未能有系统能实现，区块链技术确让大家看到了希望，以太坊引入智能合约，实现经济活动的可编程性和抹除金融中介。
```suggestion
超前的概念，在当时未能有系统能实现，区块链技术却让大家看到了希望，以太坊引入智能合约，实现经济活动的可编程性和抹除金融中介。
```

2019-01-14 15:31 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +以太坊衍生了**Token 经济**，是区块链技术从只能进行数字货币的转移时代迈入了智能合约时代。
```suggestion
以太坊衍生了**Token 经济**，使区块链技术从只能进行数字货币的转移时代迈入了智能合约时代。
```

2019-01-14 15:41 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +**以太坊是可编程的区块链**，不同于比特币中预设的货币转移操作。在以太坊中用户可自定义一份操作，以满足自身业务需求。从而可以在以太坊网络中部署运行风格各异的应用程序，此时以太坊便是一个应用平台，是分散的、去中心化的。
这里说“可编程”就是指代能写智能合约来自定义交易规则，不是指代自定义区块链设置等。为何会让你对“可编程”有不同理解？

我认为本书的目标人群是软件开发者，因此不需要进一步解释非区块链相关的术语和概念。如果有必要解释，可以提供标注注释。 

你的意见呢？

2019-01-14 15:42 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +一份自定义操作如何得以运行，依赖的是以太坊内置的可编程性。以太坊中定义并实现一套这些操作指令行为协议，协议内嵌在以太坊程序中，当交易需要打包到区块中时，以太坊将启动一个包含协议的子系统，将按照交易信息让子系统执行智能合约中的操作指令。这个子系统名为“EVM”，在计算机技术上称之为“虚拟机”，在沙盒环境中正确执行操作指令，是“图灵完备的”。
```suggestion
一份自定义操作如何得以运行，依赖的是以太坊内置的可编程性。
以太坊中定义并实现一套这些操作指令行为协议，协议内嵌在以太坊程序中，
当交易需要打包到区块中时，以太坊将启动一个包含协议的子系统，
将按照交易信息让子系统执行智能合约中的操作指令。
这个子系统名为“EVM”(Ethereum Virtual Machine)，在计算机技术上称之为“虚拟机”，
在沙盒环境中正确执行操作指令，是“图灵完备的”。
```

2019-01-14 15:53 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +这样，开发者便可以利用熟悉的编程语言编写可以运行在以太坊虚拟机上的应用。以太坊作为分布式的区块链网络，所有交易均在所有节点中由虚拟机以相同的指令执行。
下面修改如何？ 我希望即说明你可以自己DIV实现编译，又可以借助已有编程语言来开发智能合约。
```suggestion
这样，开发者便可以利用熟悉的编程语言将业务逻辑代码编译成以太坊虚拟机可识别的指令来运行应用。
当然，以太坊生态中已经有成熟的智能合约专用编程语言 Solidity、Viper等来帮助开发者快速开发、调式智能合约。
以太坊作为分布式的区块链网络，所有交易均在所有节点中由虚拟机以相同的指令执行。
```

2019-01-14 16:08 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +以太坊是全新的、开源的、具有智能合约功能的区块链技术系统（如比特币），尝试构建基于交易的状态机。同时，以太坊致力于为开发者提供一个紧密整合的的端到端系统，这个系统提供一个可信对象消息传递技术框架，使开发者可以用一种前所未有的计算范式来构建应用。其最重要目标是促进那些原本无法信任对方的个体之间的交易。以太坊的在数字货币领域的创新，标致着区块链2.0的到来。
改成这样呢？
```suggestion
以太坊是借鉴比特币实现的第一个去中心化应用运行平台，平台开源且生态繁荣。
平台目标是提供一个安全、紧密整合各种服务的P2P网络系统，促进个体之间的交易，特别是互不信任的双方交易。
开发者可以基于此平台，使用加密货币加智能合约范式来构建应用。

以太坊的在加密货币领域的创新，标致着区块链2.0的到来。
```

2019-01-15 04:54 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +1. 以太坊公链在2015年7月30日启动。最初的以太坊版本称为边境（Frontier，也有“前锋”的意思），用的是工作量证明（proof-of-work）算法，但未来预期会转换成权益证明（proof-of-stake）。此时的以太坊还不太成熟，但是可以进行基本的挖矿，学习和试验。系统运行之后，吸引了更多的人关注并参与到开发中来，以太坊作为一个应用平台，需要更多的人去开发自己的去中心化应用来实现
```suggestion
1. 以太坊公链在2015年7月30日启动。最初的以太坊版本称为边境（Frontier，也有“前锋”的意思），用的是工作量证明（proof-of-work）算法，但未来预期会转换成权益证明（proof-of-stake）。
此时的以太坊还不太成熟，但是可以进行基本的挖矿，学习和试验。
系统运行之后，吸引了更多的人关注并参与到开发中来。
以太坊作为一个应用平台，需要更多的人去开发自己的去中心化应用来实现以太坊本身的价值。
随着人气渐旺，以太坊的价值也水涨船高。
```

2019-01-16 02:41 UTC, gitferry requested changes
还有上次review的几处没有改

2019-01-16 02:41 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +以太坊是全新的、开源的、具有智能合约功能的区块链技术系统（如比特币），尝试构建基于交易的状态机。同时，以太坊致力于为开发者提供一个紧密整合的的端到端系统，这个系统提供一个可信对象消息传递技术框架，使开发者可以用一种前所未有的计算范式来构建应用。其最重要目标是促进那些原本无法信任对方的个体之间的交易。以太坊的在数字货币领域的创新，标致着区块链2.0的到来。
我稍微润色一下。个人认为以太坊的目标是改善在区块链之上的开发环境，而安全交易这个目标比特币已经实现了，而且“紧密整合各种服务”太笼统了。

“以太坊在比特币的基础上进一步发展，目前已经成为最受欢迎的智能合约平台。以太坊团队的目标是构建一个对开发者更友好、更易于创新的区块链系统，这也是以太坊生态系统如此繁荣的重要原因。想要参与到区块链浪潮当中的开发者无需对区块链的专业知识就可以在以太坊平台上编写智能合约，搭建属于自己的去中心化应用。以太坊的诞生是区块链技术发展史上的重要里程碑，使得区块链在非金融领域的普遍应用成为可能，同时也被认为是区块链2.0时代的标识。”

2019-01-16 02:41 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +**以太坊是可编程的区块链**，不同于比特币中预设的货币转移操作。在以太坊中用户可自定义一份操作，以满足自身业务需求。从而可以在以太坊网络中部署运行风格各异的应用程序，此时以太坊便是一个应用平台，是分散的、去中心化的。
可以可以，我之前是觉得没听过“可编程区块链”这个说法，但其实表达的意思大家都明白

2019-01-17 04:51 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +因此，区块链作为分布式数据库就能在整个网络中维持一致。所有交易活动受到密码保护，利用程序化的经济激励来刺激更多的人来维护和验证网络，保障区块链的安全与去中心化。
```suggestion
因此，区块链作为分布式数据库就能在整个网络中维持一致。
所有交易都会被签名以保证不可抵赖性，利用程序化的经济激励来刺激更多的人来维护和验证网络，保障区块链的安全与去中心化。
```

2019-01-17 04:54 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +比特币系统视为一个分布式账本，账本中记录着每个账户的资金流水，可实时统计账户余额并通过交易将比特币进行转移，实现个体间无需信任基础和第三方中介的金融活动。比特币简单有效的解决了分布式网络的共识问题，随着更多开发者关注，极客们希望将比特币系统用于数字货币转移之外的其他经济活动。
```suggestion
比特币系统视为一个分布式账本，账本中记录着每笔交易动态，通过交易签名将比特币进行转移，实现个体间无需信任基础和第三方中介的金融活动。
比特币简单有效的解决了分布式网络的共识问题，随着更多开发者关注，极客们希望将比特币系统用于数字货币转移之外的其他经济活动。
```

2019-01-17 04:56 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +2014年， Vitalik Buterin 和 Gavin Wood、Jeffrey Wilcke 完成新平台的架构设计与运行规则，通过实施图灵完备的语言实现一个区块链架构的可编程的智能合约平台，该平台即为当前高热度的以太坊。
```suggestion
2014年， Vitalik Buterin 和 Gavin Wood、Jeffrey Wilcke 完成新平台的架构设计与运行规则，试图构建一个内置图灵完备的编程语言的智能合约平台。该平台即为当前高热度的以太坊。
```

2019-01-17 04:58 UTC, ysqi reviewed
@gitferry 我补充了遗漏部分，你可以直接同意无意见部分，其他继续沟通。

2019-01-17 06:19 UTC, gitferry requested changes

2019-01-17 06:19 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +区块链基于分布式网络架构，每个网络节点都按照设定的程序执行并记录相同的交易。交易依次被组装在一个区块中，节点每次只能增加一个区块链，而每个区块通过密码学技术联系在一起。并利用密码学技术保证交易安全。
后来仔细读了这一段话，发现有很多问题。
1. 从专业角度来说，区块链网络是P2P的网络，并不是分布式网络。因为从技术角度来说，分布式网络（distributed network）是类似于Hadoop这样的分布式中心网络（distributed centralized network）。也就是说，实际上通常意义上说的分布式系统是有中心的，只不过由多台服务器共同工作而已。
2. ”每个网络节点都按照设定的程序执行并记录相同的交易。“这句话会让人误以为区块链是个同步系统。但实际上区块链是典型的异步系统，因为网络延迟的存在，每个节点收到的交易都不会完全相同。在经过PoW共识之后，每个节点都会维护一个最长链，这样就能保证当交易被确认的次数足够多的时候，相同高度的区块中的交易是相同的。
3. “节点每次只能增加一个区块链”多了一个“链”字，另外，这里说每次只能增加一个区块也是不正确的，因为有的节点可能网络延迟，节点高度可能落后较多，但当网络状况突然改善时，它可以向其它节点一次请求多个区块，从而赶上“进度”。但我明白你这里其实是想说“在区块链的每个共识周期内只会有一个区块产生。”
4. “并利用密码学技术保证交易安全。”这句话不正确，因为区块链中的交易安全主要是由共识算法保证的（防止双花等），区块链中的密码学技术主要包括非对称加密和哈希算法，作用分别是提供不可抵赖性和不可篡改性，密码学算是共识算法的一部分，可以说它间接保证了交易的安全。

2019-01-17 06:19 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +因此，区块链作为分布式数据库就能在整个网络中维持一致。所有交易活动受到密码保护，利用程序化的经济激励来刺激更多的人来维护和验证网络，保障区块链的安全与去中心化。
跟上面一样，说区块链是“分布式数据库”也不准确，可以说它是去中心化的系统（decentralised system）。

2019-01-17 06:19 UTC, gitferry commented on content/basic/ethereum/whatEthereum.md
> +以太坊是全新的、开源的、具有智能合约功能的区块链技术系统（如比特币），尝试构建基于交易的状态机。同时，以太坊致力于为开发者提供一个紧密整合的的端到端系统，这个系统提供一个可信对象消息传递技术框架，使开发者可以用一种前所未有的计算范式来构建应用。其最重要目标是促进那些原本无法信任对方的个体之间的交易。以太坊的在数字货币领域的创新，标致着区块链2.0的到来。
这里还没有给反馈和修改。

2019-01-19 04:48 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +以太坊是全新的、开源的、具有智能合约功能的区块链技术系统（如比特币），尝试构建基于交易的状态机。同时，以太坊致力于为开发者提供一个紧密整合的的端到端系统，这个系统提供一个可信对象消息传递技术框架，使开发者可以用一种前所未有的计算范式来构建应用。其最重要目标是促进那些原本无法信任对方的个体之间的交易。以太坊的在数字货币领域的创新，标致着区块链2.0的到来。
```suggestion
以太坊在比特币的基础上进一步发展，目前已经成为最受欢迎的智能合约平台。
以太坊团队的目标是构建一个对开发者更友好、更易于创新的区块链系统，这也是以太坊生态系统如此繁荣的重要原因。
想要参与到区块链浪潮当中的开发者无需对区块链的专业知识就可以在以太坊平台上编写智能合约，搭建属于自己的去中心化应用。

以太坊的诞生是区块链技术发展史上的重要里程碑，使得区块链在非金融领域的普遍应用成为可能，同时也被认为是区块链2.0时代的标识。
```

2019-01-19 04:52 UTC, ysqi commented on content/basic/ethereum/whatEthereum.md
> +区块链基于分布式网络架构，每个网络节点都按照设定的程序执行并记录相同的交易。交易依次被组装在一个区块中，节点每次只能增加一个区块链，而每个区块通过密码学技术联系在一起。并利用密码学技术保证交易安全。
同意你的意见，实则是写法不严谨，在多个概念中模糊混淆。

2019-01-19 18:47 UTC, gitferry approved these changes
总体上看没啥问题了

2019-01-21 07:06 UTC, merged